//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundDb2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fund
    {
        public int fundId { get; set; }
        public string fundName { get; set; }
        public int customerID { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
