//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundDb2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class fundEntitiesConnectionString : DbContext
    {
        public fundEntitiesConnectionString()
            : base("name=fundEntitiesConnectionString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fund> Funds { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<ViewCustomer> ViewCustomers { get; set; }
    
        public virtual ObjectResult<FundDetails> GetFunds(Nullable<int> param1)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FundDetails>("GetFunds", param1Parameter);
        }
    }
}
