//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundDb2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCustomer
    {
        public int customerID { get; set; }
        public string customerName { get; set; }
        public Nullable<int> fundCnt { get; set; }
    }
}
